spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: system
        uri: http://127.0.0.1:9001
        predicates:
        - Path=/system/**
      - id: business
        uri: lb://business
        predicates:
        - Path=/business/**
      - id: file
        uri: lb://file
        predicates:
        - Path=/file/**
server:
  port: 9000
eureka:
  client:
    service-url:
      dafaultZone: http://localhost:8761/eureka/
